on:
  schedule:
   - cron: '0 0 * * 1'
  push:
    # branches:
    #   - master

jobs:
  publish_archive_job:
    runs-on: ubuntu-latest
    name: A job to publish zulip-archive in GitHub pages
    steps:
      - uses: actions/checkout@v2
      - name: install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install Python dependencies
        run: python -m pip install --upgrade pip urllib3 certifi requests PyGithub gitpython toml bs4
    - name: install Lean
      run: |
        curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- -y
        echo "::add-path::$HOME/.elan/bin"
      - name: install leanproject 
        run: sudo pip3 install mathlibtools\
      - name: upgrade project
        run: leanproject up
      - name: build project 
        run: lean src
      - name: push changes
        run: |
          git commit -am "auto update Lean/mathlib versions"
          git push
